config/routes.rb
Sisfa::Application.routes.draw do
  get "clientes/autocomplete"
  get "productos/autocomplete"
  get "hospitalizacion_registros/autocomplete"
  get "productos/autocomplete_producto_compra"
  get "productos/inventario"
  get "productos/caducado"
  get "productos/alerta"
  get "proveedors/autocomplete"
  get "facturas/index_compra"
  get "facturas/index_anulada"
  get "hospitalizacion_registros/reporte"
  get "pacientes/autocomplete"
  get "pacientes/autocomplete_fisiatria"
  get "pacientes/civil"
  get "pacientes/militar"
  get "pacientes/familiar"
  get "doctors/autocomplete"
  get "doctors/dashboard"
  get "jornada_morbilidads/reporte"
  get "enfermedads/autocomplete"
  get "jornada_preventivas/reporte"
  get "emergencia_parte_mensuals/reporte"
  get "dashboard_hospital/index"
  get "dashboard_hospital/estadisticas_hoy"
  get "dashboard_hospital/estadisticas_mes"
  get "turnos/hoy"
  get "turnos/manana"
  get "dashboard_hospital/ingresados"
  get "dashboard_enfermeria/index"
  get "panel_aplication/index"
  get "traspasos/index_anulada"
  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  get "reportes/reporte_total"
  get "reportes/liquidaciones"
  get "reportes/cierre_caja_mensual"
  get "reportes/cierre_caja_diario"
  get "turnos/consulta_turnos"
  get "turnos/consulta_resultados"
  #fisiatria
  get "calendario/index"
  get "calendario/next_month"
  get "calendario/prev_month"
  get "calendario/current_month"
  get "item_tratamientos/autocomplete"
  get "resultado_tratamientos/by_day"
  get "resultado_tratamientos/hour_and_day"
  get "personals/by_day"
  get "asignar_horarios/autocomplete"
  get "asignar_horarios/reporte_ingresados"
  get "asignar_horarios/view_edit"
  get "reportes_fisiatria/index"
  get "reportes_fisiatria/personal"
  get "reportes_fisiatria/search_paciente"
  get "reportes_fisiatria/paciente"
  get "reportes_fisiatria/paciente_certificado"
  get "reportes_fisiatria/factura"
  get "configuraciones_fisiatria/horarios"
  get "configuraciones_fisiatria/tratamientos"
  get "configuraciones_fisiatria/certificados"
  get "configuraciones_fisiatria/index"
  get "admin_medical_records/index"
  get "admin_medical_records/hospitalizaciones"
  get "admin_medical_records/emergencias"
  get "admin_medical_records/consultas"

  resources :emisors, except: [:show, :destroy, :index] do
    member do
      get 'turnos_otros_dias'
      post 'update_turnos_fisiatria'
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy] do
    member do
      post "suspender"
    end
  end
  resources :ingreso_productos, only: [:new, :create] do
    resources :canjes, only: [:new, :create]
  end
  resources :pacientes, except: [:new] do
    resources :hospitalizacion_registros, :only => [:new, :create, :edit, :update, :destroy]
    resources :emergencia_registros, except: [:index]
    get "view_edit"
    get "print_historia"
    get "terapias"
    get 'reporte', :on => :collection
  end
  resources :turnos, except: [:show] do
    resources :consulta_externa_morbilidads, :only => [:new, :create]
    resources :consulta_externa_preventivas, :only => [:new, :create]
  end
  resources :condicions, :only => [:show]
  resources :clientes do
    get "proformas/receta"
  end
  resources :consulta_externa_morbilidads, :only => [:show]
  resources :proveedors, except: [:destroy]
  resources :hospitalizacion_registros, except: [:destroy] do
    resources :asignacion_camas
    member do
      post "dar_alta_enfermeria"
    end
  end
  resources :nota_enfermeras, :only => [:show]
  resources :item_nota_enfermeras, only: [:create, :edit, :update]
  resources :entrega_turnos, except: [:edit, :update] do
    get "view_create_item"
    resources :item_entrega_turnos, only: [:create, :destroy]
  end
  resources :signo_vitals, :only => [:show]
  resources :item_signo_vitals, only: [:create, :edit, :update]
  resources :item_facturas
  resources :item_proformas
  resources :traspasos, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :item_traspasos
  resources :cuartos, except: [:show, :edit, :update]
  resources :camas, only: [:create, :destroy]
  resources :hospitalizacions, :only => [:index, :show] do
    get "show_pedido"
    get 'pedidos', :on => :collection
  end
  resources :item_hospitalizacions, only: [:create] do
    member do
      post "despachar"
      get "anular"
      post "anulado"
    end
  end
  resources :factura_compras, only: [:show, :new, :create]
  resources :product_imports, only: [:new, :create]
  resources :cliente_imports, only: [:new, :create]
  resources :informacion_adicional_pacientes, :only => [:update]
  resources :revisions
  resources :doctors, except: [:show] do
    resources :jornada_morbilidads, only: [:new, :create, :index]
    resources :jornada_preventivas, only: [:new, :create, :index]
    member do
      post "suspender"
    end
  end
  resources :productos, except: [:destroy] do
    resources :kardexes, :as => "kardex", only: [:index]
  end
  resources :facturas, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :proformas, except: [:edit, :update, :destroy] do
    member do
      post "facturar"
    end
  end
  resources :cierre_cajas, only: [:new, :index] do
    member do
      get "print_and_close"
    end
  end
  resources :reportes, only: [:index]
  root 'panel_aplication#index'
  resources :tratamientos
  resources :personals do
    member do
      post "suspender"
    end
  end
  resources :horarios do
    member do
      post "suspender"
    end
  end
  resources :asignar_horarios do
   member do
      post "dar_alta"
    end
  end
  resources :resultado_tratamientos
  resources :item_tratamientos, only: [:edit, :update, :new, :create] do
    member do
      post "suspender"
    end
  end
  resources :fisiatria_configuracions, only: [:edit, :update]
end

app/models/traspaso.rb
# == Schema Information
#
# Table name: traspasos
#
#  id            :integer          not null, primary key
#  servicio      :string(255)
#  fecha_emision :date             not null
#  numero        :integer          not null
#  iva           :float            not null
#  total         :float            not null
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  subtotal      :float            not null
#  entregado_a   :string(255)
#  subtotal_12   :float            not null
#  razon_anulada :string(255)
#  anulado       :boolean          default(FALSE)
#

class Traspaso < ActiveRecord::Base
	has_many :item_traspasos
	has_many :ingreso_productos, :through => :item_traspasos
  belongs_to :user

	accepts_nested_attributes_for :item_traspasos

	#validations
  validates :servicio, :user_id, :numero, :iva, :total,:fecha_emision, :entregado_a, presence: true
  validates :total, :numericality => { :greater_than_or_equal_to => 0}
  validates :numero, :numericality => { only_integer: true }

  #callbacks
  before_validation :set_transpaso_values, on: :create
  after_save :add_liquidacion

	#methods
	def self.disminuir_stock (item_traspasos)
		item_traspasos.each do |item|
			unless item.producto_id.nil?
				producto  = Producto.find(item.producto_id)
				producto.cantidad_disponible -= item.cantidad
				producto.save
			end
		end
	end

  def set_transpaso_values
    self.numero = Traspaso.last ? Traspaso.last.numero + 1 : 1
    self.fecha_emision = Time.now
		subtotal = 0
		subtotal_12 = 0
		iva = 0
		self.item_traspasos.each do |item|
			unless item.ingreso_producto_id.nil?
				ingreso = IngresoProducto.find item.ingreso_producto_id
				cantidad = item.cantidad #obtiene la cantidad del producto
				item.valor_unitario = ingreso.producto.precio_venta #asigna el valor del item
				item.total = (ingreso.producto.precio_venta * cantidad).round(2) #asigna valor total del item
				if ingreso.producto.hasiva == true
					subtotal_12 = subtotal_12 + item.total
					item.iva = (cantidad * (ingreso.producto.precio_venta * 0.12).round(2))
				else
					subtotal = subtotal + item.total
					item.iva = 0
				end
				iva = iva + item.iva #suma iva de los productos
			end
		end
		self.iva = iva.round(2)
		self.subtotal = subtotal
		self.subtotal_12 = subtotal_12
		self.total = self.subtotal + self.subtotal_12 + self.iva
		self.total = self.total.round(2)
  end

	def rollback_traspaso
		self.item_traspasos.each do |item|
			ingreso_producto = item.ingreso_producto
			ingreso_producto.cantidad = ingreso_producto.cantidad + item.cantidad
			ingreso_producto.producto.stock = ingreso_producto.producto.stock + item.cantidad #suma al stock si se anula
			Lineakardex.create(:kardex => ingreso_producto.producto.kardex, :tipo => "Entrada", :fecha => Time.now, :cantidad => item.cantidad, :v_unitario => item.ingreso_producto.producto.precio_venta, :modulo => "Ingreso de: " + self.servicio, :observaciones => "Transferencia anulada" )
			ingreso_producto.save
			ingreso_producto.producto.save
		end
	end

	def anular_traspaso(razon)
		self.anulado = true
		self.razon_anulada = razon
		self.rollback_traspaso
		self.save
	end

  def add_liquidacion
  	total = 0
  	self.item_traspasos.each do |item|
  		ingreso = IngresoProducto.find item.ingreso_producto_id
  		total = total + (ingreso.producto.precio_compra * item.cantidad).round(2)
  		#obtine el total de la venta sin ganacia
  	end
  	Liquidacion.add_traspaso(self, total)
  end
end

app/controllers/traspasos_controller.rb
class TraspasosController < ApplicationController
	before_filter :require_login
  before_filter :is_admin_or_vendedor_farmacia
  before_action :find_traspaso, :only =>[:show, :anular, :anulado]

	 def index
    respond_to do |format|
      format.html
      format.json { render json: TraspasosDatatable.new(view_context, "no_anulada") }
    end
  end

  def index_anulada
		respond_to do |format|
			format.html
      format.json { render json: TraspasosDatatable.new(view_context, "anulada") }
		end
	end

	def new
		@traspaso = Traspaso.new
		@traspaso.item_traspasos.build
		respond_to do |format|
      format.html
      format.js
    end
	end

	def create
		respond_to do |format|
			@traspaso = Traspaso.new(traspaso_params.merge(user_id: current_user.id))
			@traspaso.save
  		format.js
		end	
	end

	def show
		respond_to do |format|
      format.js
      format.pdf do
				render :pdf => "proforma", :layout => 'report.html', :template => "traspasos/traspaso_pdf.html.erb"
			end
    end
	end
	
	def anular
		respond_to do |format|
			format.js
		end
	end

	def anulado
		unless @traspaso.anulado
			@traspaso.anular_traspaso(params[:razon])
			redirect_to traspasos_path, :notice => "Transferencia Anulada"
		end
	end

	private

	def traspaso_params
		params.require(:traspaso).permit :servicio,
		:fecha_emision,
		:numero,
		:subtotal,
		:iva,
		:total,
		:user_id,
		:entregado_a,
		:item_traspasos_attributes => [
			:cantidad,
			:valor_unitario,
			:iva,
			:total,
			:ingreso_producto_id
		]
	end

	def find_traspaso
		@traspaso = Traspaso.find(params[:id])
	end
	
end

app/views/traspasos/_anuladas.html.erb
<div class="table-responsive">
<table id="anulada" class="data-table table-bordered dataTable" data-source="<%= traspasos_index_anulada_url(format: "json") %>">
  <thead>
    <tr>
      <th>Número</th>
      <th>Fecha</th>
      <th>Dependencia</th>
      <th>Emisor</th>
      <th>Recibido</th>
      <th>Razón anulada</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>

app/views/traspasos/_anular.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3 class="modal-title" id="myModalLabel">Anular Transferencia</h3>
</div>
<%= form_tag anulado_traspaso_path do %>
<div class="modal-body ">
	<%= label_tag :razon, "Porque desea anular este transferencia?" %>
	<%= text_area_tag :razon, params[:razon], :required => true, class: "form-control", :placeholder => "Ejm: Producto emitido equivocado" %>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= submit_tag "Anular",data: { confirm: 'Esta seguro?' }, class: "btn btn-danger" %>
</div>
<% end %>

app/views/traspasos/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Información</h1>
</div>
<div class="modal-body">
	 <p>
    <strong>Dependencia:</strong>
    <%= @traspaso.servicio%>
  </p>
  <p>
    <strong>Fecha de Emisión:</strong>
    <%= @traspaso.fecha_emision %>
  </p>
  <table class="table table-hover">
	  <thead class= "well">
	    <tr>
	      <th>Producto</th>
	      <th>Cantidad</th>
	      <th>Precio</th>
	      <th>Iva</th>
	      <th>Total</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @traspaso.item_traspasos.each do |t| %>
	      <tr>
	        <td><%= t.ingreso_producto.producto.nombre%></td>
	        <td><%= t.cantidad %></td>
	        <td>$ <%= t.valor_unitario %></td>
	        <td>$ <%= t.iva %></td>
	        <td>$ <%= t.total %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
  <div class="row">
    <div class="col-xs-2 col-xs-offset-8">
      <p>
        <strong>
          Sub 12: <br>
          Sub 0: <br>
          IVA: <br>
          Total: <br>
        </strong>
      </p>
    </div>
    <div class="col-xs-2">
      <strong>
        $ <%= @traspaso.subtotal_12 %><br>
        $ <%= @traspaso.subtotal %><br>
        $ <%= @traspaso.iva %><br>
        $ <%= @traspaso.total %><br>
      </strong>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
</div>

app/views/traspasos/_transferencias.html.erb
<div class="table-responsive">
<table class="data-table table-bordered" data-source="<%= traspasos_url(format: "json") %>">
	<thead>
		<tr>
			<th>Número</th>
			<th>Dependencia</th>
			<th>Emisor</th>
			<th>Recibido</th>
			<th>Fecha</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>
</div>

app/views/traspasos/anular.js.erb
m = $('#content_modal');
m.html('<%= j(render 'anular', traspaso: @traspaso) %>');

app/views/traspasos/create.js.erb
<%- if @traspaso.errors.any? %>
  <%- @traspaso.errors.full_messages.each do |msg|%>
      alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $.getScript("/traspasos/<%= @traspaso.id%>");
  $('#myModal').modal({
    remote: "",
    backdrop: "static",
    keyboard: false
  });
  $('#myModal').on("shown.bs.modal", function() {
    $('.modal-footer').html('<a class="print_button looks_like_button btn btn-info reset-fields" href="/traspasos/<%= @traspaso.id%>.pdf" target="_blank"><i class="fa fa-print"></i>  Imprimir</a>')
    window.Helpers.ResetFields.init();
  });
  alertify.success("Transferencia Guardada");
<%- end %>

app/views/traspasos/index.html.erb
<div class="row shadow">
	<div class="col-md-12">
		<div class="title-red-head">
			<span>
				<i><%= link_to "",  new_traspaso_path, title:'Nueva', class: "ttip fa fa-plus" %></i>
			</span>
			<span class="rev-combo pull-right"><i class="fa fa-exchange"></i></span>
		</span>
		<h3>LISTA DE TRANSFERENCIAS</h3>
	</div><br>
	<div class="transferencias-table">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#todas" data-toggle="tab">Emitidas</a></li>
			<li><a href="#anuladas" data-toggle="tab">Anuladas</a></li>
		</ul><br>
		<div class="tab-content">
			<div class="tab-pane active" id="todas">
				<%= render "traspasos/transferencias"%>
			</div>
			<div class="tab-pane" id="anuladas">
				<%= render "traspasos/anuladas"%>
			</div>
		</div>
	</div>
</div>

app/views/traspasos/new.html.erb
<div class="row col-md-8 shadow col-md-offset-2">
	<div class="col-md-12">
		<div class="title-red-head">
			<span>
				<i><%= link_to "", traspasos_path, title:'Ver Transferencias', class: "ttip fa fa-list" %></i>
			</span>
			<h3>Transferencia Interna</h3>
			<span class="rev-combo pull-right fecha_sin_hora"></span>
		</div>
	</div>
	<div class="comprobante">
		<%= nested_form_for @traspaso, :html => {id: "form-traspaso"}, :remote => true do |f| %>
		<%= form_errors_for @traspaso %>
		<div class="row-fix-div col-md-12">
			<div class="col-md-3 col-xs-3 icon-transferencia-center">
				<i class="fa fa-exchange fa-4x"></i><br>
				<small>transferencia</small>
			</div>
			<div class="col-md-8 col-xs-8">
				<%= f.text_field :entregado_a, :class => "form-control selecttag",:placeholder => "Entregado a:" %>
				<%= f.select :servicio, options_for_select(["Medicina Interna","Cardiología","Ginecología","Gastroenterología","Dermatología","Rayos X","Farmacia","Central de Enfermería","Estadística","Financiero","Traumatología","Odontología","Laboratorio Clínico","Fisiatría","Pediatría"]), {}, { class: "select-servicio form-control"}%>
				<h6 class="text-muted">Emitido por: <%= current_user.username%></h6>
			</div>
		</div>
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table" id="traspaso">
					<thead class = "text-center">
						<th class="col-md-5">Producto</th>
						<th>V.Unit</th>
						<th>Iva</th>
						<th>Cantidad</th>
						<th>Total</th>		
						<th></th>		
					</thead>
					<tbody>
						<%= f.fields_for :item_traspasos, :wrapper => false do |b| %>
						<tr class="fields productos_traspaso">
							<%= render 'item_traspasos/item_traspaso', f: b %>
							<% end %>
						</tr>
						<tr>
							<td>
								<%= f.link_to_add "Producto", :item_traspasos, :class => "nuevo_new_default"%>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="col-md-9">
					<h4 class="text-right">Total <strong class= "total">$00.00</strong></h4>
				</div>
				<div class="col-md-3">
					<%= f.submit :Guardar, class: " btn btn-block btn-info", data: {disable_with: "Almacenando"}%>			
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/traspasos/show.js.erb
m = $('#content_modal');
m.html('<%= j(render 'show', trasferencia: @trasferencia) %>');
window.Helpers.ButtonsHelper.init();

app/views/traspasos/traspaso_pdf.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6">
			<h4><strong>TRANSFERENCIA #<%= @traspaso.numero%></strong></h4>
			<h5>Dependencia: <%= @traspaso.servicio%></h5>
			<h5>Emitido por: <%= @traspaso.user.username%></h5>
			<h5>Entregado a: <%= @traspaso.entregado_a%></h5>
			<h5>Fecha de emision: <%= @traspaso.fecha_emision %></h5>
		</div>
		<div class="col-xs-6 text-right">
				<h4><strong>HOSPITAL BASICO 7 B.I LOJA</strong><h4>
				<h6>Correo: hb7loja2012@gmail.com</h6>
				<h6>Telefono: (07) 257-0254</h6>
				<h6 class="text-muted">*Documento de uso interno</h6>
			</div>
		</div>
		<table class="table table-bordered">
			<thead class="well">
				<tr>
					<th>Producto</th>
					<th>Cantidad</th>
					<th>Precio</th>
					<th>Iva</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @traspaso.item_traspasos.each do |item| %>
				<tr>
					<td><%= item.ingreso_producto.producto.nombre%></td>
					<td><%= item.cantidad %></td>
					<td><%= item.valor_unitario %></td>
					<td><%= item.iva%></td>
					<td class="text-right"><%= item.total %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="row text-right">
			<div class="col-xs-2 col-xs-offset-8">
				<p>
					<strong>
						Subtotal 12: <br>
						Subtotal 0 : <br>
						IVA : <br>
						Total : <br>
					</strong>
				</p>
			</div>
			<div class="col-xs-2">
				<strong>
					$ <%= @traspaso.subtotal_12 %><br>
					$ <%= @traspaso.subtotal %><br>
					$ <%= @traspaso.iva %><br>
					$ <%= @traspaso.total %><br>
				</strong>
			</div>
		</div>
	</div>
</div>