config/routes.rb
Sisfa::Application.routes.draw do
  get "clientes/autocomplete"
  get "productos/autocomplete"
  get "hospitalizacion_registros/autocomplete"
  get "productos/autocomplete_producto_compra"
  get "productos/inventario"
  get "productos/caducado"
  get "productos/alerta"
  get "proveedors/autocomplete"
  get "facturas/index_compra"
  get "facturas/index_anulada"
  get "hospitalizacion_registros/reporte"
  get "pacientes/autocomplete"
  get "pacientes/autocomplete_fisiatria"
  get "pacientes/civil"
  get "pacientes/militar"
  get "pacientes/familiar"
  get "doctors/autocomplete"
  get "doctors/dashboard"
  get "jornada_morbilidads/reporte"
  get "enfermedads/autocomplete"
  get "jornada_preventivas/reporte"
  get "emergencia_parte_mensuals/reporte"
  get "dashboard_hospital/index"
  get "dashboard_hospital/estadisticas_hoy"
  get "dashboard_hospital/estadisticas_mes"
  get "turnos/hoy"
  get "turnos/manana"
  get "dashboard_hospital/ingresados"
  get "dashboard_enfermeria/index"
  get "panel_aplication/index"
  get "traspasos/index_anulada"
  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  get "reportes/reporte_total"
  get "reportes/liquidaciones"
  get "reportes/cierre_caja_mensual"
  get "reportes/cierre_caja_diario"
  get "turnos/consulta_turnos"
  get "turnos/consulta_resultados"
  #fisiatria
  get "calendario/index"
  get "calendario/next_month"
  get "calendario/prev_month"
  get "calendario/current_month"
  get "item_tratamientos/autocomplete"
  get "resultado_tratamientos/by_day"
  get "resultado_tratamientos/hour_and_day"
  get "personals/by_day"
  get "asignar_horarios/autocomplete"
  get "asignar_horarios/reporte_ingresados"
  get "asignar_horarios/view_edit"
  get "reportes_fisiatria/index"
  get "reportes_fisiatria/personal"
  get "reportes_fisiatria/search_paciente"
  get "reportes_fisiatria/paciente"
  get "reportes_fisiatria/paciente_certificado"
  get "reportes_fisiatria/factura"
  get "configuraciones_fisiatria/horarios"
  get "configuraciones_fisiatria/tratamientos"
  get "configuraciones_fisiatria/certificados"
  get "configuraciones_fisiatria/index"
  get "admin_medical_records/index"
  get "admin_medical_records/hospitalizaciones"
  get "admin_medical_records/emergencias"
  get "admin_medical_records/consultas"

  resources :emisors, except: [:show, :destroy, :index] do
    member do
      get 'turnos_otros_dias'
      post 'update_turnos_fisiatria'
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy] do
    member do
      post "suspender"
    end
  end
  resources :ingreso_productos, only: [:new, :create] do
    resources :canjes, only: [:new, :create]
  end
  resources :pacientes, except: [:new] do
    resources :hospitalizacion_registros, :only => [:new, :create, :edit, :update, :destroy]
    resources :emergencia_registros, except: [:index]
    get "view_edit"
    get "print_historia"
    get "terapias"
    get 'reporte', :on => :collection
  end
  resources :turnos, except: [:show] do
    resources :consulta_externa_morbilidads, :only => [:new, :create]
    resources :consulta_externa_preventivas, :only => [:new, :create]
  end
  resources :condicions, :only => [:show]
  resources :clientes do
    get "proformas/receta"
  end
  resources :consulta_externa_morbilidads, :only => [:show]
  resources :proveedors, except: [:destroy]
  resources :hospitalizacion_registros, except: [:destroy] do
    resources :asignacion_camas
    member do
      post "dar_alta_enfermeria"
    end
  end
  resources :nota_enfermeras, :only => [:show]
  resources :item_nota_enfermeras, only: [:create, :edit, :update]
  resources :entrega_turnos, except: [:edit, :update] do
    get "view_create_item"
    resources :item_entrega_turnos, only: [:create, :destroy]
  end
  resources :signo_vitals, :only => [:show]
  resources :item_signo_vitals, only: [:create, :edit, :update]
  resources :item_facturas
  resources :item_proformas
  resources :traspasos, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :item_traspasos
  resources :cuartos, except: [:show, :edit, :update]
  resources :camas, only: [:create, :destroy]
  resources :hospitalizacions, :only => [:index, :show] do
    get "show_pedido"
    get 'pedidos', :on => :collection
  end
  resources :item_hospitalizacions, only: [:create] do
    member do
      post "despachar"
      get "anular"
      post "anulado"
    end
  end
  resources :factura_compras, only: [:show, :new, :create]
  resources :product_imports, only: [:new, :create]
  resources :cliente_imports, only: [:new, :create]
  resources :informacion_adicional_pacientes, :only => [:update]
  resources :revisions
  resources :doctors, except: [:show] do
    resources :jornada_morbilidads, only: [:new, :create, :index]
    resources :jornada_preventivas, only: [:new, :create, :index]
    member do
      post "suspender"
    end
  end
  resources :productos, except: [:destroy] do
    resources :kardexes, :as => "kardex", only: [:index]
  end
  resources :facturas, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :proformas, except: [:edit, :update, :destroy] do
    member do
      post "facturar"
    end
  end
  resources :cierre_cajas, only: [:new, :index] do
    member do
      get "print_and_close"
    end
  end
  resources :reportes, only: [:index]
  root 'panel_aplication#index'
  resources :tratamientos
  resources :personals do
    member do
      post "suspender"
    end
  end
  resources :horarios do
    member do
      post "suspender"
    end
  end
  resources :asignar_horarios do
   member do
      post "dar_alta"
    end
  end
  resources :resultado_tratamientos
  resources :item_tratamientos, only: [:edit, :update, :new, :create] do
    member do
      post "suspender"
    end
  end
  resources :fisiatria_configuracions, only: [:edit, :update]
end

app/models/paciente.rb
# == Schema Information
#
# Table name: pacientes
#
#  id                      :integer          not null, primary key
#  tipo                    :string(255)
#  grado                   :string(255)
#  estado                  :string(255)
#  codigo_issfa            :string(255)
#  pertenece_a             :string(255)
#  unidad                  :string(255)
#  parentesco              :string(255)
#  cliente_id              :integer
#  created_at              :datetime
#  updated_at              :datetime
#  n_hclinica              :integer
#  fecha_hclinica          :date
#  jefe_de_reparto         :string(255)
#  afiliado                :string(255)
#  discapacidad            :string(255)
#  antecedentes_personales :string(255)
#  antecedentes_familiares :string(255)
#  registrado_por          :string(255)
#

class Paciente < ActiveRecord::Base

	belongs_to :cliente
	has_one :horario
	has_many :condicions, dependent: :destroy
	has_many :turnos, dependent: :destroy
	has_many :hospitalizacion_registros, dependent: :destroy
	has_many :asignar_horarios
	has_many :resultado_tratamientos
	has_one :informacion_adicional_paciente, dependent: :destroy
	has_many :necesita_terapias
	accepts_nested_attributes_for :cliente, :informacion_adicional_paciente

	delegate :nombre, :direccion, :telefono, :email, :numero_de_identificacion, :sexo, :fecha_de_nacimiento, :estado_civil, :to => :cliente, :prefix => true

	#callbacks

	#validation
	validates :tipo, :n_hclinica, :presence => true
	validates :cliente_id, :uniqueness =>  { :message => "Esta persona ya tiene una historia clinica" }
	validates :n_hclinica, :uniqueness =>  true
	validates :grado, :estado, :pertenece_a, :unidad, :presence => true, :if => "tipo == 'militar'"
	validates :codigo_issfa, :presence => true, :if => "tipo == 'militar' or tipo == 'familiar'"
	validates :parentesco, :presence => true, :if => "tipo == 'familiar'"
#methods
def cliente_attributes=(attributes)
	if attributes['id'].present?
		self.cliente = Cliente.find(attributes['id'])
	end
	super
end

#class methods
def self.autocomplete(params)
	pacientes = Paciente.includes(:cliente).where("clientes.nombre like ?", "%#{params}%").references(:cliente).limit(10)
	pacientes = pacientes.map do |paciente|
		{
			:id => paciente.id,
			:label => paciente.cliente.nombre + " / " + "H.C:" + paciente.n_hclinica.to_s,
			:value => paciente.cliente.nombre,
			:nombre => paciente.cliente.nombre,
			:cliente_id => paciente.cliente.id,
			:n_hclinica => paciente.n_hclinica
		}
	end
	pacientes
end

def self.autocomplete_fisiatria(params)
	pacientes = Paciente.includes(:cliente).where("clientes.nombre like ?", "%#{params}%").references(:cliente).limit(10)
	pacientes = pacientes.map do |paciente|
		if paciente.necesita_terapias.last.nil?
		{
			:id => paciente.id,
			:label => paciente.cliente.nombre + " / " + "H.C:" + paciente.n_hclinica.to_s,
			:value => paciente.cliente.nombre,
			:nombre => paciente.cliente.nombre,
			:cliente_id => paciente.cliente.id,
			:n_hclinica => paciente.n_hclinica
		}
		else
		{
			:id => paciente.id,
			:label => paciente.cliente.nombre + " / " + "H.C:" + paciente.n_hclinica.to_s,
			:value => paciente.cliente.nombre,
			:nombre => paciente.cliente.nombre,
			:cliente_id => paciente.cliente.id,
			:n_hclinica => paciente.n_hclinica,
			:diagnostico => paciente.necesita_terapias.last.consulta_externa_morbilidad.diagnostico_sindrome,
			:doctor => paciente.necesita_terapias.last.consulta_externa_morbilidad.nombre_medico
		}
		end
	end
	pacientes
end

def self.last_terapia_fisiatria(paciente)
	terapias = paciente.asignar_horarios.last
end

def self.medical_records(paciente)
	p = Paciente.find(paciente)
	registros = p.condicions + p.hospitalizacion_registros.where(:alta => true)
	registros = registros.sort_by(&:created_at)
end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_filter :require_login
  before_filter :is_admin_or_auxiliar_estadistica, :except => [:show, :view_edit, :edit, :update, :print_historia, :autocomplete, :autocomplete_fisiatria]
  before_filter :shared_permission, :only => [:show, :view_edit, :edit, :update]
	before_action :set_paciente, only: [:edit, :update, :destroy]
	before_action :new_paciente, only: [:civil, :militar, :familiar]

	def index
		respond_to do |format|
			format.html
			format.json { render json: PacientesDatatable.new(view_context) }
		end
	end

	def autocomplete
		respond_to do |format|
			format.json { render :json => Paciente.autocomplete(params[:term]) }
		end
	end

	def autocomplete_fisiatria
		respond_to do |format|
			format.json { render :json => Paciente.autocomplete_fisiatria(params[:term]) }
		end
	end

	def reporte
		@pacientes = Paciente.all.includes(:cliente).order('n_hclinica asc')
		respond_to do |format|
			format.html
			format.pdf do
				render :pdf => "historias clinicas", :layout => 'report.html', :template => "pacientes/reporte.pdf.erb", :orientation => 'Landscape'
			end
		end
	end

	def civil
		@paciente.tipo = "civil"
	end

	def militar
		@paciente.tipo = "militar"
		@paciente.afiliado = "ISSFA"
	end

	def familiar
		@paciente.tipo = "familiar"
		@paciente.afiliado = "ISSFA"
	end

	def view_edit
		@paciente = Paciente.includes(:cliente, :informacion_adicional_paciente).where(:id => params[:paciente_id]).references(:cliente, :informacion_adicional_paciente).first
	end

	def print_historia
		@paciente = Paciente.includes(:cliente, :informacion_adicional_paciente, :condicions).where(:id => params[:paciente_id]).references(:cliente, :informacion_adicional_paciente, :condicions).first
		respond_to do |format|
			format.pdf do
				render :pdf => "historia", :layout => 'report.html', :template => "pacientes/print_historia.pdf.erb"
			end
		end
	end

	def show
		@paciente = Paciente.includes(:cliente, :informacion_adicional_paciente).where(:id => params[:id]).references(:cliente, :informacion_adicional_paciente).first
		@registros = Paciente.medical_records(@paciente)
	end

	def terapias
		@paciente = Paciente.find(params[:paciente_id])
		@terapias = @paciente.asignar_horarios
	end

	def create
		@paciente = Paciente.new(paciente_params.merge(:fecha_hclinica => Time.now, :registrado_por => current_user.cliente.nombre + " / usuario: " + current_user.username))
		if @paciente.save
			redirect_to pacientes_path, :notice => "Almacenado"
		else
			case @paciente.tipo
			when "civil"
				render 'civil'
			when "familiar"
				render 'familiar'
			when "militar"
				render 'militar'
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			@paciente.update(paciente_params)
			format.json { respond_with_bip(@paciente) }
		end
	end

	def destroy
		@paciente.destroy
		respond_to do |format|
			format.html { redirect_to pacientes_url }
		end
	end

	private

	def paciente_params
		params.require(:paciente).permit :tipo,
		:n_hclinica,
		:grado,
		:estado,
		:codigo_issfa,
		:pertenece_a,
		:unidad,
		:parentesco,
		:jefe_de_reparto,
		:afiliado,
		:discapacidad,
		:antecedentes_personales,
		:antecedentes_familiares,
		:cliente_attributes => [
			:id,
			:fecha_de_nacimiento,
			:nombre,
			:direccion,
			:telefono,
			:numero_de_identificacion,
			:sexo,
			:edad,
			:estado_civil,
			:ocupacion
			],
			:informacion_adicional_paciente_attributes => [
				:parroquia,
				:provincia,
				:canton,
				:raza,
				:nacionalidad,
				:familiar_parentesco,
				:familiar_cercano,
				:familiar_direccion,
				:familiar_telefono,
				:observacion,
				:paciente_id,
				:representante_legal
			]
		end

		def set_paciente
			@paciente = Paciente.find(params[:id])
		end

		def new_paciente
			@paciente= Paciente.new
			@paciente.build_cliente
			@paciente.build_informacion_adicional_paciente
		end
end

app/helpers/pacientes_helper.rb
module PacientesHelper

	def age(date)
		birthday = date
		now = Time.now.utc.to_date
		now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
	end

	def exact_age(birthday)
		if birthday != nil
			y=(Date.today.year) - (birthday.year)
			m=(Date.today.month)-(birthday.month)
			d=(Date.today.day)-(birthday.day)
			tipo=""
		case
		when (m<0)
			age= (y-1).to_s + " años"
		when (m==0)
			if y==0
				age=d.to_s + " dias" #recien nacido menos de 1 mes del año actual
			else
				age=y.to_s + " años"	
			end
		when (m>0)
			if y==0
				age=m.to_s + " meses" # recien nacido mayor a 1 mes del año actual
			else	
				age=y.to_s + " años"
			end
		end
		age			
		else
			return "Sin Fecha Nac."
		end
	end
end

app/views/pacientes/_historia_registros.html.erb
<div class="row info-paciente">
	<legend><i class="fa fa-stethoscope"></i> Registros Medicos
		<span class="pull-right">
			<%= link_to "TERAPIAS", paciente_terapias_path(@paciente), class: "label label-success" %></span></legend>
	<ul class="cbp_tmtimeline">
		<% @registros.each do |r|  %>
		<% if r.has_attribute?(:alta)%>
		<li>
			<time class="cbp_tmtime">
				<span><%= local_date(r.created_at, "date")%></span>
			</time>
			<div class="cbp_tmicon fa-hospital-o"></div>
			<div class="cbp_tmlabel">
				<small>DIAGNOSTICO</small>
				<h3><%= r.diagnostico_salida%></h3>
				<p>Motivo Ingreso: <%= r.diagnostico_ingreso%></p>
				<p>Medico: <%= r.medico_asignado %></p>
				<p>Tipo: Hospitalizacion</p>
				<p><%= link_to "Ver registro", r, :remote => true,  :rel => 'tooltip', 'data-toggle' =>  "modal", 'data-target' => '#myModal',  class: "btn btn-default btn-xs" %></p>
			</div>
		</li>
	</li>
	<% else %>
	<li>
		<time class="cbp_tmtime">
			<span><%= local_date(r.created_at, "date")%></span>
		</time>
		<% case r.tipo_registro%>
		<% when "Emergencia"%>
		<div class="cbp_tmicon fa-plus"></div>
		<% when "Consulta Externa Morbilidad"%>
		<div class="cbp_tmicon fa-stethoscope"></div>
		<% when "Consulta Externa Preventiva"%>
		<div class="cbp_tmicon fa-stethoscope"></div>
		<% end %>
		<div class="cbp_tmlabel">
			<small>DIAGNOSTICO</small>
			<h3><%= r.diagnostico_1%></h3>
			<p>Motivo: <%= r.motivo_de_consulta%></p>
			<p>Medico: <%= r.medico_asignado %></p>
			<p>Tipo: <%= r.tipo_registro %></p>
			<p><%= link_to "Ver registro", r, :remote => true,  :rel => 'tooltip', 'data-toggle' =>  "modal", 'data-target' => '#myModal',  class: "btn btn-default btn-xs" %></p>
		</div>
	</li>
	<li></li>
	<% end %>
	<% end %>
</ul>
</div>

app/views/pacientes/_informacion_consulta.html.erb
<div class="container">
	<div class="col-md-6 row-fix-div datos-paciente">
		<div class="col-md-4 text-center">
			<% if @turno.paciente.cliente_sexo == "Femenino" %>
			<span class ="fa fa-female fa-5x"></span><br>
			<% else %>
			<span class ="fa fa-male fa-5x"></span><br>				
			<% end %>
			<br>
			<%= link_to 'Actualizar Datos', paciente_view_edit_path(@turno.paciente),{:target => '_blank', class: "ttip btn btn-info btn-xs"}%>
		</div>
		<div class="col-md-8">
			<h4><strong><%= @turno.paciente.cliente_nombre %></strong></h4>
			<small><strong>HISTORIA CLINICA: #</strong><%=@turno.paciente.n_hclinica%></small><br>
			<small><strong>DISCAPACIDAD: </strong> <%= best_in_place @turno.paciente, :discapacidad, type: :select, collection: [['Ninguna', 'Ninguna'],['Fisica','Fisica'],['Intelectual','Intelectual'],['Mental','Mental'],['Auditiva','Auditiva'],['Visual','Visual'],['Otra','Otra']] %></small> <span class="fa fa-pencil text-info">..</span><br>
			<small><strong>EDAD:</strong>
				<%= exact_age(@turno.paciente.cliente_fecha_de_nacimiento) %> <small class="text-muted"><%= @turno.paciente.cliente_fecha_de_nacimiento %></small>
			</small><br>
			<small><strong>NACIONALIDAD: </strong><%= @turno.paciente.informacion_adicional_paciente.nacionalidad%></small>
		</div>
	</div>
	<div class="col-md-5">
		<i class="fa fa-info-circle"></i> <label><strong> Antecedentes Personales</strong></label> <span class="fa fa-pencil text-info">..</span><br>
		<%= best_in_place @turno.paciente, :antecedentes_personales,{:classes => "area-max", :type => :textarea, :nil => "El paciente no tiene registrado antecedentes personales.!!"} %><br>
		<i class="fa fa-info-circle"></i> <label><strong> Antecedentes Familiares</strong></label> <span class="fa fa-pencil text-info">..</span><br>
		<%= best_in_place @turno.paciente, :antecedentes_familiares,{:classes => "area-max", :type => :textarea, :nil => "El paciente no tiene registrado antecedentes familiares.!!"} %><br><br>
		<%= link_to ' Ver Historia Clinica', @turno.paciente,{:target => '_blank'}%>
	</div>
</div>

app/views/pacientes/_informacion_hospitalizacion.html.erb
<div class="container">
	<div class="col-md-6 row-fix-div datos-paciente">
		<div class="col-md-4 text-center">
			<% if @registro.paciente.cliente_sexo == "Femenino" %>
			<span class ="fa fa-female fa-5x"></span><br>
			<% else %>
			<span class ="fa fa-male fa-5x"></span><br>				
			<% end %>
			<br>
			<%= link_to 'Actualizar Datos', paciente_view_edit_path(@registro.paciente),{:target => '_blank', class: "ttip btn btn-info btn-xs"}%>

		</div>
		<div class="col-md-8">
			<h4><strong><%= @registro.paciente.cliente_nombre %></strong></h4>
			<small><strong>HISTORIA CLINICA: #</strong><%=@registro.paciente.n_hclinica%></small><br>
			<small><strong>DISCAPACIDAD: </strong> <%= best_in_place @registro.paciente, :discapacidad, type: :select, collection: [['Ninguna', 'Ninguna'],['Fisica','Fisica'],['Intelectual','Intelectual'],['Mental','Mental'],['Auditiva','Auditiva'],['Visual','Visual'],['Otra','Otra']] %></small> <span class="fa fa-pencil text-info">..</span><br>
			<small><strong>EDAD:</strong>
				<%= exact_age(@registro.paciente.cliente_fecha_de_nacimiento) %> <small class="text-muted"><%= @registro.paciente.cliente_fecha_de_nacimiento %></small>
			</small><br>
			<small><strong>NACIONALIDAD: </strong><%= @registro.paciente.informacion_adicional_paciente.nacionalidad%></small>
		</div>
	</div>
	<div class="col-md-5">
		<i class="fa fa-info-circle"></i> <label><strong> Antecedentes Personales</strong></label> <span class="fa fa-pencil text-info">..</span><br>
		<%= best_in_place @registro.paciente, :antecedentes_personales,{:classes => "area-max", :type => :textarea, :nil => "El paciente no tiene registrado antecedentes personales.!!"} %><br>
		<i class="fa fa-info-circle"></i> <label><strong> Antecedentes Familiares</strong></label> <span class="fa fa-pencil text-info">..</span><br>
		<%= best_in_place @registro.paciente, :antecedentes_familiares,{:classes => "area-max", :type => :textarea, :nil => "El paciente no tiene registrado antecedentes familiares.!!"} %><br><br>
			<%= link_to ' Ver Historia Clinica', @registro.paciente,{:target => '_blank'}%>
	</div>
</div>

app/views/pacientes/_pacientes.html.erb
<table class="data-table-not-search-column table-bordered" data-source="<%= pacientes_url(format: "json") %>">
  <thead>
    <tr>
      <th class="col-md-1">H.Clinica</th>
      <th class="col-md-3">Nombre</th>
      <th>Cedula</th>
      <th>Tipo</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/pacientes/index.html.erb
<div class="row title-history">
	<h3 class="text-center">Administracion de Pacientes</h3>
</div>
<div class="row info-paciente">
	<div class="acciones">
		<div class="well well-sm">
			<strong><small>Crear Historia Clinica:</small></strong>
			<%=link_to("Militar", pacientes_militar_path, class: "nuevo_new btn-xs")%>
			<%=link_to("Familiar", pacientes_familiar_path, class: "nuevo_new btn-xs")%>
			<%=link_to("Civil", pacientes_civil_path, class: "nuevo_new btn-xs")%>
			<%=link_to("PDF Pacientes", reporte_pacientes_path(:format => "pdf"), class: "btn btn-success btn-xs", target: "_blank")%>
		</div>
	</div>
	<div class="table-historias" id="flip-scroll">
		<%= render 'pacientes' %>
	</div>
</div>

app/views/pacientes/reporte.pdf.erb
<h3 class="text-center">LISTA DE HISTORIAS CLINICAS</h3>
<h4>Fecha de impresion: <%= local_date(Time.now, "date") %> </h4>
<h4>Total de H.C: <%= @pacientes.count() %></h4>
<table>
	<thead>
	</thead>
	<tbody>
	</tbody>
</table>
<table class="table table-hover">
  <thead>
    <tr class="title-green-head">
      <th>H.C</th>
      <th>NOMBRE</th>
      <th>C.I / RUC</th>
      <th>TIPO</th>
      <th>DIRECCION</th>
    </tr>
  </thead>
  <tbody>
    <% @pacientes.each do |p|  %>      
    <tr>
      <td><%= p.n_hclinica %></td>
      <td><%= p.cliente.nombre %></td>
      <td><%= p.cliente.numero_de_identificacion %></td>
      <td><%= p.tipo%></td>
      <td><%= p.cliente.direccion%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pacientes/show.html.erb
<div class="row title-history">
	<h1 class="fix-margin">Historia Clinica # <%= @paciente.n_hclinica%></h1>
</div>
<div class="row info-paciente">
	<div class="container">
		<div class="col-md-5 row-fix-div">
			<div class="col-md-4 text-center">
				<% if @paciente.cliente_sexo == "Femenino" %>
				<span class ="fa fa-female fa-5x"></span><br>
				<% else %>
				<span class ="fa fa-male fa-5x"></span><br>				
				<% end %>
				<span>
				<%= link_to "Imprimir", paciente_print_historia_path(@paciente, :format => 'pdf'), :target => "_blank",class: "label label-info" %></span>
			</div>
			<div class="col-md-8">
				<h4><strong><%= @paciente.cliente_nombre %></strong></h4>
				<small class="genero"><strong>GENERO:</strong><%= (@paciente.cliente_sexo).upcase%></small><br>
				<small><strong>EDAD:</strong>
					<%= exact_age(@paciente.cliente_fecha_de_nacimiento) %> <small class="text-muted"><%= @paciente.cliente_fecha_de_nacimiento %></small>
				</small><br>
				<small><strong>NACIONALIDAD:</strong>ECUATORIANO</small>
			</div>
		</div>
		<div class="col-md-3 col-xs-6">
			<small class="text-muted">LOCALIZACION</small><br>
			<i class="fa fa-map-marker"></i> <%= @paciente.cliente_direccion%><br/>
			<i class="fa fa-phone"></i> <%= @paciente.cliente_telefono%><br/>
			<i class="fa fa-envelope malito"></i> <%= @paciente.cliente_email%><br/>
		</div>
		<div class="col-md-3 col-xs-6">
			<small class="text-muted">CONTACTO/RELACION</small><br>
			<span><strong><%= @paciente.informacion_adicional_paciente.familiar_cercano%> /
				<small class="text-muted"><%= @paciente.informacion_adicional_paciente.familiar_parentesco%></small></strong></span><br>
				<i class="fa fa-map-marker"></i> <%= @paciente.informacion_adicional_paciente.familiar_direccion%><br/>
				<i class="fa fa-phone"></i> <%= @paciente.informacion_adicional_paciente.familiar_telefono%><br/>
			</div>
		</div>
	</div>
	<%= render 'historia_registros' %>
</div>

app/views/pacientes/view_edit.html.erb
<small class="text-info">* Haz click sobre los campos que desees editar</small>
<%= render 'informacion_paciente'  %>