config/routes.rb
Sisfa::Application.routes.draw do
  get "clientes/autocomplete"
  get "productos/autocomplete"
  get "hospitalizacion_registros/autocomplete"
  get "productos/autocomplete_producto_compra"
  get "productos/inventario"
  get "productos/caducado"
  get "productos/alerta"
  get "proveedors/autocomplete"
  get "facturas/index_compra"
  get "facturas/index_anulada"
  get "hospitalizacion_registros/reporte"
  get "pacientes/autocomplete"
  get "pacientes/autocomplete_fisiatria"
  get "pacientes/civil"
  get "pacientes/militar"
  get "pacientes/familiar"
  get "doctors/autocomplete"
  get "doctors/dashboard"
  get "jornada_morbilidads/reporte"
  get "enfermedads/autocomplete"
  get "jornada_preventivas/reporte"
  get "emergencia_parte_mensuals/reporte"
  get "dashboard_hospital/index"
  get "dashboard_hospital/estadisticas_hoy"
  get "dashboard_hospital/estadisticas_mes"
  get "turnos/hoy"
  get "turnos/manana"
  get "dashboard_hospital/ingresados"
  get "dashboard_enfermeria/index"
  get "panel_aplication/index"
  get "traspasos/index_anulada"
  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  get "reportes/reporte_total"
  get "reportes/liquidaciones"
  get "reportes/cierre_caja_mensual"
  get "reportes/cierre_caja_diario"
  get "turnos/consulta_turnos"
  get "turnos/consulta_resultados"
  #fisiatria
  get "calendario/index"
  get "calendario/next_month"
  get "calendario/prev_month"
  get "calendario/current_month"
  get "item_tratamientos/autocomplete"
  get "resultado_tratamientos/by_day"
  get "resultado_tratamientos/hour_and_day"
  get "personals/by_day"
  get "asignar_horarios/autocomplete"
  get "asignar_horarios/reporte_ingresados"
  get "asignar_horarios/view_edit"
  get "reportes_fisiatria/index"
  get "reportes_fisiatria/personal"
  get "reportes_fisiatria/search_paciente"
  get "reportes_fisiatria/paciente"
  get "reportes_fisiatria/paciente_certificado"
  get "reportes_fisiatria/factura"
  get "configuraciones_fisiatria/horarios"
  get "configuraciones_fisiatria/tratamientos"
  get "configuraciones_fisiatria/certificados"
  get "configuraciones_fisiatria/index"
  get "admin_medical_records/index"
  get "admin_medical_records/hospitalizaciones"
  get "admin_medical_records/emergencias"
  get "admin_medical_records/consultas"

  resources :emisors, except: [:show, :destroy, :index] do
    member do
      get 'turnos_otros_dias'
      post 'update_turnos_fisiatria'
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy] do
    member do
      post "suspender"
    end
  end
  resources :ingreso_productos, only: [:new, :create] do
    resources :canjes, only: [:new, :create]
  end
  resources :pacientes, except: [:new] do
    resources :hospitalizacion_registros, :only => [:new, :create, :edit, :update, :destroy]
    resources :emergencia_registros, except: [:index]
    get "view_edit"
    get "print_historia"
    get "terapias"
    get 'reporte', :on => :collection
  end
  resources :turnos, except: [:show] do
    resources :consulta_externa_morbilidads, :only => [:new, :create]
    resources :consulta_externa_preventivas, :only => [:new, :create]
  end
  resources :condicions, :only => [:show]
  resources :clientes do
    get "proformas/receta"
  end
  resources :consulta_externa_morbilidads, :only => [:show]
  resources :proveedors, except: [:destroy]
  resources :hospitalizacion_registros, except: [:destroy] do
    resources :asignacion_camas
    member do
      post "dar_alta_enfermeria"
    end
  end
  resources :nota_enfermeras, :only => [:show]
  resources :item_nota_enfermeras, only: [:create, :edit, :update]
  resources :entrega_turnos, except: [:edit, :update] do
    get "view_create_item"
    resources :item_entrega_turnos, only: [:create, :destroy]
  end
  resources :signo_vitals, :only => [:show]
  resources :item_signo_vitals, only: [:create, :edit, :update]
  resources :item_facturas
  resources :item_proformas
  resources :traspasos, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :item_traspasos
  resources :cuartos, except: [:show, :edit, :update]
  resources :camas, only: [:create, :destroy]
  resources :hospitalizacions, :only => [:index, :show] do
    get "show_pedido"
    get 'pedidos', :on => :collection
  end
  resources :item_hospitalizacions, only: [:create] do
    member do
      post "despachar"
      get "anular"
      post "anulado"
    end
  end
  resources :factura_compras, only: [:show, :new, :create]
  resources :product_imports, only: [:new, :create]
  resources :cliente_imports, only: [:new, :create]
  resources :informacion_adicional_pacientes, :only => [:update]
  resources :revisions
  resources :doctors, except: [:show] do
    resources :jornada_morbilidads, only: [:new, :create, :index]
    resources :jornada_preventivas, only: [:new, :create, :index]
    member do
      post "suspender"
    end
  end
  resources :productos, except: [:destroy] do
    resources :kardexes, :as => "kardex", only: [:index]
  end
  resources :facturas, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :proformas, except: [:edit, :update, :destroy] do
    member do
      post "facturar"
    end
  end
  resources :cierre_cajas, only: [:new, :index] do
    member do
      get "print_and_close"
    end
  end
  resources :reportes, only: [:index]
  root 'panel_aplication#index'
  resources :tratamientos
  resources :personals do
    member do
      post "suspender"
    end
  end
  resources :horarios do
    member do
      post "suspender"
    end
  end
  resources :asignar_horarios do
   member do
      post "dar_alta"
    end
  end
  resources :resultado_tratamientos
  resources :item_tratamientos, only: [:edit, :update, :new, :create] do
    member do
      post "suspender"
    end
  end
  resources :fisiatria_configuracions, only: [:edit, :update]
end

app/models/doctor.rb
# == Schema Information
#
# Table name: doctors
#
#  id             :integer          not null, primary key
#  especialidad   :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  cantidad_turno :integer
#  suspendido     :boolean          default(FALSE)
#  cliente_id     :integer
#

class Doctor < ActiveRecord::Base
	#relations
	belongs_to :cliente
	has_many :emergencia_registros
	has_many :hospitalizacion_registros
	has_many :jornada_morbilidads
	has_many :jornada_preventivas
	has_many :emergencia_parte_mensuals
	has_many :turnos
	has_many :consulta_externa_morbilidads, :through => :turnos
	has_many :consulta_externa_preventivas, :through => :turnos
	accepts_nested_attributes_for :cliente
	
	delegate :nombre, :to => :cliente, :prefix => true
	#	validations
	validates :especialidad, :cantidad_turno, :presence => true
	validates :cliente_id, :uniqueness => {:message => "Ya esta registrado como doctor"}
	# validates :cantidad_turno, :numericality => { :greater_than => 0 }
	
	#methods
	def cliente_attributes=(attributes)
		if attributes['id'].present?
    	self.cliente = Cliente.find(attributes['id'])
  	end
  super
	end

	def self.autocomplete(params)
		doctores = Doctor.includes(:cliente).where("suspendido = false and nombre like ?", "%#{params}%").references(:cliente)
    doctores = doctores.map do |doctor|
      {
        :id => doctor.id,
        :label => doctor.cliente_nombre + " / " + doctor.especialidad,
        :value => doctor.cliente_nombre,
        :nombre => doctor.cliente_nombre,
        :especialidad => doctor.especialidad
      }
    end
    doctores
	end

	def self.turnos_doctores
		doctores = []
		self.includes(:cliente, :turnos).where("suspendido = false and cantidad_turno != 0").each do |doctor|
			num_turnos = unless doctor.turnos.last_turno.nil? then doctor.turnos.last.numero else 0 end
			doctores << {
				:nombre =>doctor.cliente_nombre,
				:turnos_emitidos => num_turnos,
				:turnos_disponibles => doctor.cantidad_turno - num_turnos,
				:especialidad => doctor.especialidad
				}
		end
		doctores
	end

	def self.list_turnos_all_doctor
		doctores = []
		self.includes(:turnos, :cliente).each do |doctor|
			turno = doctor.turnos.turnos_today
			unless turno.compact.empty?
				doctores << {
					:nombre =>doctor.cliente_nombre,
					:turnos => turno
				}
			end
		end
		doctores
	end

	def self.list_turnos_query(fecha)
		doctores = []
		self.includes(:turnos, :cliente).each do |doctor|
			turno = doctor.turnos.turnos_query(fecha)
			unless turno.compact.empty?
				doctores << {
					:nombre =>doctor.cliente_nombre,
					:turnos => turno
				}
			end
		end
		doctores
	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_filter :require_login
  before_filter :shared_permission, except: [:dashboard]
  before_filter :is_doctor, only: [:dashboard]
	before_action :set_doctor, only: [:edit, :update, :destroy, :turnos_dia, :turnos_manana, :suspender]

	def index
		@doctores = Doctor.includes(:cliente).all
	end

	def dashboard
		@doctor = current_user.cliente.doctor
		@turnos_hoy = @doctor.turnos.turnos_today
		@turnos_manana = @doctor.turnos.turnos_tomorrow
		@emergencias = @doctor.emergencia_registros.ingresados
		@hospitalizados = @doctor.hospitalizacion_registros.ingresados
		@enviado = @doctor.jornada_morbilidads.was_send
		@enviado_preventiva = @doctor.jornada_preventivas.was_send
	end

	def autocomplete
    respond_to do |format|
      format.json { render :json => Doctor.autocomplete(params[:term]) }
    end
  end

	def new
		@doctor = Doctor.new
		@doctor.build_cliente
    respond_to do |format|
      format.js
    end
	end

  def suspender
    if @doctor.suspendido
      @doctor.suspendido = false
    else
      @doctor.suspendido = true
    end
    @doctor.save
    redirect_to doctors_path, :notice => "Doctor modificado"
  end

	def edit
		respond_to do |format|
      format.js
    end
	end

	def create
		@doctor = Doctor.new(doctor_params)
    respond_to do |format|
      @doctor.save
      format.js {
				@doctores = Doctor.all
      	render "success"
      }
    end
	end

  def update
    respond_to do |format|
      @doctor.update(doctor_params)
      format.html
      format.js {
				@doctores = Doctor.all
      	render "success"
      }
    end
  end

	def destroy
		@doctor.destroy
		respond_to do |format|
			format.html { redirect_to doctors_url }
		end
	end

	private

	def set_doctor
		@doctor = Doctor.find(params[:id])
	end

	def doctor_params
		params.require(:doctor).permit :especialidad,
		 :cantidad_turno,
		 :suspendido,
		 :cliente_attributes => [
				:id,
				:nombre,
				:direccion,
				:telefono,
				:numero_de_identificacion
			]
	end
end

app/views/doctors/partials/_doctors.html.erb
<% @doctores.each do |doctor|  %>
<li class= "ingresado-item items">
	<div class="doctor">
		<span class="internado-name">
			<span <%= 'style= text-decoration:line-through;' if doctor.suspendido %>><%=  doctor.cliente_nombre %></span>
		</span>
		<span class="internado-hc">
			<%= doctor.especialidad  %>
		</span>
		<div class="pull-right">
			<span class="opcions">
				<span class="cama-number">
					<small class="text-muted">
						<% if doctor.cantidad_turno == 0 %>
						No atiende turnos
						<% else %>
						#Turnos: <%= doctor.cantidad_turno %>
						<% end %>
					</small>
				</span>
				<span class="menu">
					<ul class="list-inline">
						<li class="btn-circle">
							<% if doctor.suspendido %>
							<%= link_to '', suspender_doctor_path(doctor), method: :post, data: { confirm: 'Esta seguro de activar este doctor?' },:rel => 'tooltip', :title => 'Activar', class: "ttip fa fa-thumbs-up text-muted text-success"%>
							<% else %>
							<%= link_to '', suspender_doctor_path(doctor), method: :post, data: { confirm: 'Esta seguro de suspender este doctor?' },:rel => 'tooltip', :title => 'Suspender', class: "ttip fa fa-thumbs-down"%>
							<% end %>
						</li>
						<li class="btn-circle">
							<%= link_to "", doctor, method: :delete, data: { confirm: 'Esta seguro de eliminar este doctor?' }, class: "ttip fa fa-times-circle text-danger",:rel=> 'tooltip', :title=>'Eliminar' %>
						</li>
					</ul>
				</span>
			</span>
			<span class="ingresado-type">
				<%= link_to "", edit_doctor_path(doctor), {:remote => true, :rel=> 'tooltip', :title=>'Editar','data-toggle' =>  "modal", 'data-target' => '#myModal', class: "ttip fa fa-user-md text-info"} %>
			</span>
		</div>
	</div>
</li>
<% end %>

app/views/doctors/partials/_emergencia.html.erb
<% unless @emergencias.empty?  %>
<h4 class="fa fa-plus-square text-danger"> Emergencia</h4>
<ul class="list-group">
	<% @emergencias.each do |t|  %>
	<li class="list-group-item item-turnos" <%= 'style= background-color:#7CC576;color:#fff;' if t.registrado %>>
		<ul class="list-inline text-center">
			<li class=" col-md-2 col-xs-2 datos-turno"><spam>E</spam></li>
			<li class=" col-md-8 col-xs-8 border-lines">
				<h4><%=t.paciente.cliente_nombre%></h4>
			</li>
		</ul>
		<% unless t.registrado %>
		<span class="show-menu">
			<span class="fa fa-chevron-right"></span>
		</span>
		<ul class="list-group-submenu">
			<li class="list-group-submenu-item"><%= link_to '', t.paciente, :rel => 'tooltip', :title => 'Historia Clinica', :target => "_blank", class: "fa fa-h-square"%></li>
			<li class="list-group-submenu-item danger"><%= link_to "", edit_paciente_emergencia_registro_path(t.paciente, t), { :rel=> 'tooltip', :title=>'Llenar Diagnostico', class: "fa fa-plus-square"} %></li>
		</ul>	
		<% end %>
	</li>
	<% end %>
</ul>
<% end %>

app/views/doctors/partials/_form.html.erb
<div class="modal-header">
	<h3 class="modal-title" id="myModalLabel">Doctor</h3>
</div>
<%= form_for @doctor, :remote => true do |f| %>
<div class="modal-body field">
	<%= f.fields_for :cliente do |cliente_params| %>
	<%=  cliente_params.hidden_field :id, class: "cliente_id" %>
	<%=  cliente_params.label :numero_de_identificacion%>
	<%=  cliente_params.text_field :numero_de_identificacion, class: " identificacion_cliente", :placeholder => "Cédula o RUC" %>
	<%=  cliente_params.label :nombre%>
	<%=  cliente_params.text_field :nombre, class: " nombre", :placeholder => "Nombres Apellidos" %>
	<%=  cliente_params.label :direccion%>
	<%=  cliente_params.text_field :direccion, class: "direccion", :placeholder => "direccion"%>
	<%=  cliente_params.label :telefono%>
	<%=  cliente_params.text_field :telefono, class: "telefono", :placeholder => "Teléfono"%>
	<% end %>
	<%= f.label :especialidad%>
	<%= f.text_field :especialidad, placeholder: "Especialidad" %>
	<%= f.label :cantidad_turno%>
	<%= f.text_field :cantidad_turno, placeholder: "Cantidad de turnos" %>
	<small class="text-warning"> * Ingrese 0 si no acepta turnos</small>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= f.submit 'Guardar', class: "btn btn-primary", :remote => true %>
</div>
<% end %>

app/views/doctors/partials/_hospitalizados.html.erb
<% unless @hospitalizados.empty?  %>
<h4 class="fa fa-hospital-o text-success"> Hospitalizados</h4>
<ul class="list-group">
	<% @hospitalizados.each do |t|  %>
	<li class="list-group-item item-turnos">
		<ul class="list-inline text-center">
			<li class=" col-md-2 col-xs-2 datos-turno"><spam>H</spam></li>
			<li class=" col-md-8 col-xs-8 border-lines">
				<h4><%=t.paciente.cliente_nombre%></h4>
			</li>
		</ul>
		<span class="show-menu">
			<span class="fa fa-chevron-right"></span>
		</span>
		<ul class="list-group-submenu">
			<li class="list-group-submenu-item"><%= link_to '', t.paciente, :rel => 'tooltip', :title => 'Historia Clinica', :target => "_blank", class: "fa fa-h-square"%></li>
			<li class="list-group-submenu-item success">
				<%= link_to "", edit_paciente_hospitalizacion_registro_path(t.paciente, t),{ :rel=> 'tooltip', :title=>'Dar de alta', class: "fa fa-check"}%>
			</li>
		</ul>	
	</li>
	<% end %>
</ul>
<% end %>

app/views/doctors/partials/_turnos_hoy.html.erb
<% if @turnos_hoy.empty? %>
<div class="text-center text-muted">
	<span class= "fa fa-ticket fa-2x"></span>
	<h5>No hay turnos registrados</h5>		
</div>
<% else %>
<ul class="list-group">
	<% @turnos_hoy.each do |t|  %>
	<li class="list-group-item item-turnos" <%= 'style= background-color:#7CC576;color:#fff;' if t.atendido %> <%= 'style= background-color:#CA6868;color:#fff;' if @enviado and @enviado_preventiva %>>
		<ul class="list-inline text-center">
			<li class=" col-md-2 col-xs-2 datos-turno"><span><%= t.numero %></span></li>
			<li class=" col-md-8 col-xs-8 border-lines">
				<h4><%=t.paciente.cliente_nombre%></h4>
			</li>
			<li class=" col-md-2 col-xs-2 text-center datos-turno">
				<% if t.numero >= 15 %>
				<span>00:00</span>
				<% else %>
				<span><%=local_date(t.hora, "time")%></span>
				<% end %>
			</li>
		</ul>
		<% unless @enviado and @enviado_preventiva %>
		<% unless t.atendido %>
		<span class="show-menu">
			<span class="fa fa-chevron-right"></span>
		</span>
		<ul class="list-group-submenu">
			<li class="list-group-submenu-item"><%= link_to '', t.paciente, :rel => 'tooltip', :title => 'Historia Clinica', :target => "_blank", class: "fa fa-h-square"%></li>
			<li class="list-group-submenu-item info">
				<% unless @enviado_preventiva %>
				<%= link_to 'P', new_turno_consulta_externa_preventiva_path(t), :rel => 'tooltip', :title => 'Consulta Preventiva'%>
				<% else %>
				<span class="fa fa-rocket"></span>
				<% end %>
			</li>
			<li class="list-group-submenu-item success">
				<% unless @enviado%>
				<%= link_to "M", new_turno_consulta_externa_morbilidad_path(t), { :rel=> 'tooltip', :title=>'Consulta Morbilidad'} %>
				<% else %>
				<span class="fa fa-rocket"></span>
				<% end %>
			</li>
		</ul>
		<% end %>
		<% end %>
	</li>
	<% end %>
</ul>
<% end %>