config/routes.rb
Sisfa::Application.routes.draw do
  get "clientes/autocomplete"
  get "productos/autocomplete"
  get "hospitalizacion_registros/autocomplete"
  get "productos/autocomplete_producto_compra"
  get "productos/inventario"
  get "productos/caducado"
  get "productos/alerta"
  get "proveedors/autocomplete"
  get "facturas/index_compra"
  get "facturas/index_anulada"
  get "hospitalizacion_registros/reporte"
  get "pacientes/autocomplete"
  get "pacientes/autocomplete_fisiatria"
  get "pacientes/civil"
  get "pacientes/militar"
  get "pacientes/familiar"
  get "doctors/autocomplete"
  get "doctors/dashboard"
  get "jornada_morbilidads/reporte"
  get "enfermedads/autocomplete"
  get "jornada_preventivas/reporte"
  get "emergencia_parte_mensuals/reporte"
  get "dashboard_hospital/index"
  get "dashboard_hospital/estadisticas_hoy"
  get "dashboard_hospital/estadisticas_mes"
  get "turnos/hoy"
  get "turnos/manana"
  get "dashboard_hospital/ingresados"
  get "dashboard_enfermeria/index"
  get "panel_aplication/index"
  get "traspasos/index_anulada"
  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  get "reportes/reporte_total"
  get "reportes/liquidaciones"
  get "reportes/cierre_caja_mensual"
  get "reportes/cierre_caja_diario"
  get "turnos/consulta_turnos"
  get "turnos/consulta_resultados"
  #fisiatria
  get "calendario/index"
  get "calendario/next_month"
  get "calendario/prev_month"
  get "calendario/current_month"
  get "item_tratamientos/autocomplete"
  get "resultado_tratamientos/by_day"
  get "resultado_tratamientos/hour_and_day"
  get "personals/by_day"
  get "asignar_horarios/autocomplete"
  get "asignar_horarios/reporte_ingresados"
  get "asignar_horarios/view_edit"
  get "reportes_fisiatria/index"
  get "reportes_fisiatria/personal"
  get "reportes_fisiatria/search_paciente"
  get "reportes_fisiatria/paciente"
  get "reportes_fisiatria/paciente_certificado"
  get "reportes_fisiatria/factura"
  get "configuraciones_fisiatria/horarios"
  get "configuraciones_fisiatria/tratamientos"
  get "configuraciones_fisiatria/certificados"
  get "configuraciones_fisiatria/index"
  get "admin_medical_records/index"
  get "admin_medical_records/hospitalizaciones"
  get "admin_medical_records/emergencias"
  get "admin_medical_records/consultas"

  resources :emisors, except: [:show, :destroy, :index] do
    member do
      get 'turnos_otros_dias'
      post 'update_turnos_fisiatria'
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy] do
    member do
      post "suspender"
    end
  end
  resources :ingreso_productos, only: [:new, :create] do
    resources :canjes, only: [:new, :create]
  end
  resources :pacientes, except: [:new] do
    resources :hospitalizacion_registros, :only => [:new, :create, :edit, :update, :destroy]
    resources :emergencia_registros, except: [:index]
    get "view_edit"
    get "print_historia"
    get "terapias"
    get 'reporte', :on => :collection
  end
  resources :turnos, except: [:show] do
    resources :consulta_externa_morbilidads, :only => [:new, :create]
    resources :consulta_externa_preventivas, :only => [:new, :create]
  end
  resources :condicions, :only => [:show]
  resources :clientes do
    get "proformas/receta"
  end
  resources :consulta_externa_morbilidads, :only => [:show]
  resources :proveedors, except: [:destroy]
  resources :hospitalizacion_registros, except: [:destroy] do
    resources :asignacion_camas
    member do
      post "dar_alta_enfermeria"
    end
  end
  resources :nota_enfermeras, :only => [:show]
  resources :item_nota_enfermeras, only: [:create, :edit, :update]
  resources :entrega_turnos, except: [:edit, :update] do
    get "view_create_item"
    resources :item_entrega_turnos, only: [:create, :destroy]
  end
  resources :signo_vitals, :only => [:show]
  resources :item_signo_vitals, only: [:create, :edit, :update]
  resources :item_facturas
  resources :item_proformas
  resources :traspasos, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :item_traspasos
  resources :cuartos, except: [:show, :edit, :update]
  resources :camas, only: [:create, :destroy]
  resources :hospitalizacions, :only => [:index, :show] do
    get "show_pedido"
    get 'pedidos', :on => :collection
  end
  resources :item_hospitalizacions, only: [:create] do
    member do
      post "despachar"
      get "anular"
      post "anulado"
    end
  end
  resources :factura_compras, only: [:show, :new, :create]
  resources :product_imports, only: [:new, :create]
  resources :cliente_imports, only: [:new, :create]
  resources :informacion_adicional_pacientes, :only => [:update]
  resources :revisions
  resources :doctors, except: [:show] do
    resources :jornada_morbilidads, only: [:new, :create, :index]
    resources :jornada_preventivas, only: [:new, :create, :index]
    member do
      post "suspender"
    end
  end
  resources :productos, except: [:destroy] do
    resources :kardexes, :as => "kardex", only: [:index]
  end
  resources :facturas, except: [:edit, :update, :destroy] do
    member do
      get "anular"
      post "anulado"
    end
  end
  resources :proformas, except: [:edit, :update, :destroy] do
    member do
      post "facturar"
    end
  end
  resources :cierre_cajas, only: [:new, :index] do
    member do
      get "print_and_close"
    end
  end
  resources :reportes, only: [:index]
  root 'panel_aplication#index'
  resources :tratamientos
  resources :personals do
    member do
      post "suspender"
    end
  end
  resources :horarios do
    member do
      post "suspender"
    end
  end
  resources :asignar_horarios do
   member do
      post "dar_alta"
    end
  end
  resources :resultado_tratamientos
  resources :item_tratamientos, only: [:edit, :update, :new, :create] do
    member do
      post "suspender"
    end
  end
  resources :fisiatria_configuracions, only: [:edit, :update]
end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id              :integer          not null, primary key
#  nombre          :string(255)      not null
#  codigo          :string(255)
#  categoria       :string(255)
#  casa_comercial  :string(255)
#  nombre_generico :string(255)
#  precio_compra   :decimal(4, 2)    not null
#  precio_venta    :decimal(4, 2)    not null
#  ganancia        :decimal(4, 2)    not null
#  hasiva          :boolean          default(FALSE)
#  stock           :integer          default(0), not null
#

class Producto < ActiveRecord::Base

#callbacks
  before_create :set_precios
  before_update :set_precios
  after_create :set_kardex

#validations
  validates :nombre, :ganancia, :precio_compra, :presence => true
  validates :nombre, :length => { :maximum => 100 }

#relations
  has_many :ingreso_productos
  has_one :kardex
  has_many :factura_compras_productos
  has_many :factura_compras, :through => :factura_compras_productos
  has_many :canjes

#nested
  accepts_nested_attributes_for :ingreso_productos, :allow_destroy => true, reject_if: :all_blank

#methods

  def self.autocomplete_producto_compra(params)
    productos = Producto.where("nombre like ?", "%#{params}%")
    productos = productos.map do |producto|
    {
      :id => producto.id,
      :label => producto.nombre + " / " + producto.casa_comercial ,
      :value => producto.nombre,
      :precio_venta => producto.precio_venta,
      :precio_compra => producto.precio_compra,
      :ganancia => producto.ganancia,
      :codigo => producto.codigo,
      :casa_comercial => producto.casa_comercial,
      :categoria => producto.categoria,
      :iva => producto.hasiva,
      :nombre_generico => producto.nombre_generico
    }
    end
    productos
  end

  def ingreso_productos_attributes=(attributes)
    cantidad = 0
    attributes.each do |value,key|
      if key[:id]
        cantidad = 0 #is update
      else
        cantidad = cantidad + key[:cantidad].to_f
      end
    end
    self.stock = self.stock + cantidad
    super
  end

  def dinero_compra
    dinero = self.precio_compra * self.stock
  end

  def dinero_venta
    dinero = self.precio_venta * self.kardex.cantidad_salida
  end

  def self.total_inventario
    total = 0
    productos = Producto.where("stock != 0")
    productos.each do |p|
      total = total + p.stock * p.precio_venta
    end
    total
  end

  private
  def set_kardex
    Kardex.create(:producto => self, :fecha => Time.now)
  end

  def set_precios
    self.precio_venta = self.precio_compra * self.ganancia/100 + self.precio_compra
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	before_filter :require_login
  before_filter :is_admin_or_vendedor_farmacia, :except => [:autocomplete]
  before_action :set_producto, only: [:show, :edit, :update]
  before_action :find_caducados, only: [:caducado, :alerta]

  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductosDatatable.new(view_context) }
    end
  end

  def autocomplete
    respond_to do |format|
      format.json { render :json => IngresoProducto.autocomplete(params[:term]) }
    end
  end

  def autocomplete_producto_compra
    respond_to do |format|
      format.json { render :json => Producto.autocomplete_producto_compra(params[:term]) }
    end
  end

  def new
    @producto=  Producto.new
    @producto.ingreso_productos.build
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def create
    @producto = Producto.new(producto_params)
    respond_to do |format|
      @producto.save
      format.js{ render "success" }
    end
  end

  def update
    respond_to do |format|
      @producto.update(producto_params)
        format.js{ render "success" }
    end
  end

  def inventario
    inventario = Producto.where("stock != 0")
    @grouped = inventario.group_by &:casa_comercial
    @total_inventario = Producto.total_inventario()
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "inventario", :layout => 'report.html', :template => "productos/inventario.html.erb"
      end
    end
  end

  def caducado
  end

  def alerta
    if @caducados.empty? == true
      redirect_to root_path
    end
  end

  private

  def producto_params
    params.require(:producto).permit :nombre,
    :nombre_generico,
    :codigo,
    :categoria,
    :casa_comercial,
    :precio_venta,
    :precio_compra,
    :ganancia,
    :hasiva,
    :ingreso_productos_attributes => [
      :lote,
      :cantidad,
      :fecha_caducidad,
      :producto_id,
      :_destroy,
      :id,
    ]
  end

  def set_producto
      @producto = Producto.find(params[:id])
  end

  def find_caducados
    @caducados = IngresoProducto.where(:fecha_caducidad =>Time.now.end_of_day..Time.now.months_since(4)).where("cantidad != '0'")
    @hoy = Date.today
  end
end

app/views/productos/_caducados.html.erb
<% if @caducados.empty? == true %>
<div class="col-md-4 col-md-offset-4 text-success text-center">
  <h3>No tienes productos caducados</h3>
  <span class="fa fa-smile-o fa-5x"></span>
</div>
<% else %>
<div class="col-md-10 col-md-offset-1">
  <h3 class= "text-muted fix-margin"> <i class ="fa fa-exclamation"></i> Por favor contacta a tu proveedor</h3>
  <% @caducados.each do |caduco|  %>
  <div class="col-md-6">
    <div class="blockquote-box blockquote-danger clearfix">
      <div class="thumbnail square pull-left">
        <% if @admin %>
        <div class="caption">
          <h5>Hacer Canje</h5>
          <i class ="fa fa-share-square-o fa-2x"></i><br/>
          <%= link_to "Canje", new_ingreso_producto_canje_path(caduco), :class => "label label-default" %>
        </div>
        <% end %>
        <span class="fa-3x"><%= caduco.producto.nombre.chr.upcase %></span>
      </div>
      <h4><%= caduco.producto.nombre %> /  <%= caduco.producto.casa_comercial %></h4>
      <h5>Cantidad: <%= caduco.cantidad %></h5>
      <h5>Fecha: <%= caduco.fecha_caducidad %></h5>
      <h6 class ="text-muted">El producto se caducará en: <strong class="days"><%=(caduco.fecha_caducidad - @hoy ).to_i%></strong> dias</h6>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/productos/_form.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3 class="modal-title" id="myModalLabel">Nuevo Producto</h3>
</div>
<%= nested_form_for @producto, :remote => true do |f| %>
<div class="modal-body">
  <div class="field">
    <div class="row">
      <div class="col-md-6">
        <%= f.hidden_field :id %>
        <%= f.label :nombre %>
        <%= f.text_field :nombre, :class => "nombre_producto"%>
      </div>
      <div class="col-md-6">
        <%= f.label :nombre_generico, "Nombre Genérico" %>
        <%= f.text_field :nombre_generico %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :codigo, "Código" %>
        <%= f.text_field :codigo %>
      </div>
      <div class="col-md-6">
        <%= f.label :categoria,"Categoría" %>
        <%= f.select(:categoria, ['MEDICAMENTO','INSUMO','QUIRURJICO'], {}, { :class => 'form-control' }) %>
      </div>
    </div>
    <%= f.label :casa_comercial %>
    <%= f.text_field :casa_comercial%>
    <div class="row">
      <div class="col-md-4">
        <%= f.label :precio_compra, "Precio de compra" %>
        <%= f.number_field :precio_compra,:class => "precio_compra", :placeholder => "0.00", min: "0", step: "any"%>
      </div>
      <div class="col-md-4">
        <%= f.label :ganancia %>
        <%= f.number_field :ganancia, :placeholder => "0.00", min: "0", :step => "any" %>
      </div>
      <div class="col-md-4 text-center">
        <%= f.label :hasiva, "Tiene IVA?" %>
        <%= f.check_box :hasiva %>
      </div>
    </div>
    <% if @producto.ingreso_productos.empty? %>
    <table class="table">
      <thead>
        <tr>
          <th>Fecha Caducidad</th>
          <th>Cantidad</th>
          <th>Lote</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :ingreso_productos, :wrapper => false do |p| %>
        <tr class="fields">
          <%= render "productos/ingresos", p: p %>
        </tr>
        <% end %>
        <tr><td><%= f.link_to_add "Compra", :ingreso_productos, :class => "nuevo_new"%></td>
        </tr>
      </tbody>
    </table>
    <% end %>
  </div>

</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/productos/_ingresos.html.erb
<td><%= p.text_field :fecha_caducidad, :class => "datepicker" %></td>
<td><%= p.number_field :cantidad,:class => "cantidad_producto",:placeholder => "0", min: "0"%></td>
<td><%= p.text_field :lote %></td>
<td><%= p.link_to_remove '', :class => "delete_destroy eliminar_item_producto" %></td>

app/views/productos/_inventario_actual.html.erb
<% if request.format.to_sym == :pdf %>
<h3 class="text-center">INVENTARIO DE PRODUCTOS ACTUAL</h3>
<h5>Fecha y Hora: <%= local_date(Time.now, "datetime")  %> </h5>
<% end %>
<table class="table table-hover">
  <thead>
    <tr class="title-green-head">
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio C</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @grouped.each do |casa_comercial, productos|  %>
    <tr>
      <th colspan="4"><%= casa_comercial%></th>
    </tr>
    <% total = 0.0 %>
    <% productos.each do |producto| %>      
    <tr>
      <td><%= producto.nombre %></td>
      <td><%= producto.stock %></td>
      <td>$<%= producto.precio_compra %></td>
      <td>$<%= producto.dinero_compra()%></td>
      <% total = total + producto.dinero_compra()%>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total casa:</strong></td> 
      <td><strong>$<%= redondear(total) %></strong></td>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total Inventario:</strong> </td>
      <td><strong>$<%= redondear(@total_inventario)  %> </strong></td>
    </tr>
  </tbody>
</table>

app/views/productos/_productos.html.erb
<table class="data-table table-bordered" data-source="<%= productos_url(format: "json") %>">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Código</th>
      <th>Casa Comercial</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/productos/_productos_form.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3 class="modal-title" id="myModalLabel">Nuevo Producto</h3>
</div>
<%= form_for(@producto, :remote => true) do |f| %>
<div class="modal-body">
	<%= f.label :nombre %>
	<%= f.text_field :nombre, class: "form-control", required:true %>
	<%= f.label :nombre_generico %>
	<%= f.text_field :nombre_generico, class: "form-control", required:true %>
	<%= f.label :cantidad_disponible %>
	<%= f.number_field :cantidad_disponible, class: "form-control", required:true %>
	<%= f.label :codigo %>
	<%= f.text_field :codigo, class: "form-control", required:true%>
	<%= f.label :Fecha_de_caducidad %>
	<%= f.text_field :fecha_de_caducidad, class: "form-control datepicker", required:true%>
	<%= f.label :categoria %>
	<%= f.text_field :categoria, class: "form-control"%>
	<%= f.label :precio_compra, "Precio de compra (sin IVA)",  class: "control-label"%>
	<%= f.number_field :precio_compra, class: "form-control", required:true, min:0 %>
	<%= f.label :casa_comercial %>
	<%= f.text_field :casa_comercial, class: "form-control"%>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/productos/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h2 class="modal-title" id="myModalLabel">Producto</h2>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-md-6">
      <strong>Nombre:</strong>
      <%= @producto.nombre %><br>
      <strong>Nombre genérico:</strong>
      <%= @producto.nombre_generico %><br>
      <strong>Casa comercial:</strong>
      <%= @producto.casa_comercial %><br>
      <strong>Categoría:</strong>
      <%= @producto.categoria %><br>
      <strong>Código:</strong>
      <%= @producto.codigo %>
    </div>
    <div class="col-md-6">
      <strong>Precio de compra:</strong>
      <%= @producto.precio_compra %><br>
      <strong>Precio de venta:</strong>
      <%= @producto.precio_venta %><br>
      <strong>Ganancia:</strong>
      <%= @producto.ganancia %> %<br>
      <strong>Incluye iva:</strong>
      <%= human_boolean @producto.hasiva%><br>
      <strong>Stock:</strong>
      <%= @producto.stock%>
    </div>
  </div>
  <% unless @producto.ingreso_productos.empty? %>
  <legend>Detalles del producto:</legend>
  <table class="table table-hover">
    <thead class= "well">
      <tr>
        <th>Lote</th>
        <th>Cantidad</th>
        <th>Fecha de caducidad</th>
      </tr>
    </thead>
    <tbody>
      <% @producto.ingreso_productos.each do |detalle| %>
      <% unless detalle.cantidad == 0 %>
      <tr>
        <td><%= detalle.lote %></td>
        <td><%= detalle.cantidad %></td>
        <td><%= detalle.fecha_caducidad %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
</div>

app/views/productos/alerta.html.erb
<%= render "caducados"  %>

app/views/productos/caducado.html.erb
<%= render "caducados"  %>

app/views/productos/index.html.erb
<div class="row shadow">
	<div class="col-md-12">
		<div class="title-green-head">
			<span><i><%=link_to "", productos_caducado_path, title: "Caducados", class: "ttip fa fa-thumbs-down"%></i></span>
		</span>
		<h3>LISTA DE PRODUCTOS</h3>
	</div><br>
	<% if @admin %>
	<%= link_to 'Inventario', productos_inventario_path, class: "print_button" %>
	<%= link_to 'Importar productos', new_product_import_path, class: "btn btn-info" %>
	<% end %>
	<div class="table-responsive table-productos">
		<%= render "productos", productos: @productos %>
	</div>
</div>

app/views/productos/inventario.html.erb
<div class="row shadow col-md-10 col-md-offset-1">
  <% unless request.format.to_sym == :pdf %>
  <div class="col-md-12">
    <div class="title-green-head">
      <span><i><%=link_to "", productos_path, class: "fa fa-arrow-left"%></i></span>
    </span>
    <h3>INVENTARIO DE PRODUCTOS</h3>
  </div><br>
  <p>
    Descargar:
    <%= link_to "PDF", productos_inventario_path(params.merge(format: 'pdf')), :target => "_blank" %>
  </p>
  <% end %>
    <%= render "productos/inventario_actual"  %>
</div>

app/views/productos/new.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'form', locals: {producto: @producto}) %>');

app/views/productos/show.js.erb
m = $('#content_modal');
m.html('<%= j(render 'show', producto: @producto) %>');

app/views/productos/success.js.erb
<%- if @producto.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  window.Helpers.ButtonsHelper.init();
  window.Helpers.FormsHelper.init()
  <%- @producto.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  $(".table-productos").html('<%= j render 'productos', productos: @productos %>');
  window.Helpers.init_datatables();
  window.Helpers.ButtonsHelper.init();
  alertify.success("Producto guardado");
<%- end %>